const products = [
    // Produk 1
    { 
        id: 1, kategori: 'Mac', name: 'Macbook Air 13" M4 (2024) - Sky Blue', specs: '16GB RAM, 256GB SSD', 
        price: 15799000, stock: 8, grade: 'Baru', sku: '7PZ3X8QA', sold: 312, 
        images: ['images/produk/id1_7PZ3X8QA/1.jpg', 'images/produk/id1_7PZ3X8QA/2.jpg', 'images/produk/id1_7PZ3X8QA/3.jpg', 'images/produk/id1_7PZ3X8QA/4.jpg', 'images/produk/id1_7PZ3X8QA/5.jpg', 'images/produk/id1_7PZ3X8QA/6.jpg', 'images/produk/id1_7PZ3X8QA/7.jpg', 'images/produk/id1_7PZ3X8QA/8.jpg'], 
        description: {
            intro: 'MacBook Air is the world’s most popular laptop for a reason’s. It delivers up to 18 hours of battery life. The M4 chip unlocks a whole new level of performance for work and play. And it now comes in a stunning Sky Blue color.',
            specs: ['Chip: Apple M4 (10-core CPU, 8-core GPU)', 
                    'Layar: 13.6-inch Liquid Retina display with True Tone',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Two Thunderbolt 4 ports, headphone jack',
                        'Color: Sky Blue' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Mantap',
                'Redesign terbaru Macbook Air, lebih Modern dan Catchy',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air 13" M4',
                '30W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 2
    { 
        id: 2, kategori: 'Mac', name: 'Macbook Air 13" M4 (2024) - Midnight', specs: '16GB RAM, 256GB SSD', 
        price: 15799000, stock: 3, grade: 'Baru', sku: 'R4K81NZB',  sold: 163,
        images: ['images/produk/id2_R4K81NZB/1.jpg', 'images/produk/id2_R4K81NZB/2.jpg', 'images/produk/id2_R4K81NZB/3.jpg', 'images/produk/id2_R4K81NZB/4.jpg', 'images/produk/id2_R4K81NZB/5.jpg', 'images/produk/id2_R4K81NZB/6.jpg', 'images/produk/id2_R4K81NZB/7.jpg'], 
        description: {
            intro: 'MacBook Air is the world’s most popular laptop for a reason’s. It delivers up to 18 hours of battery life. The M4 chip unlocks a whole new level of performance for work and play. And it now comes in a stunning Sky Blue color.',
            specs: ['Chip: Apple M4 (10-core CPU, 8-core GPU)', 
                    'Layar: 13.6-inch Liquid Retina display with True Tone',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Two Thunderbolt 4 ports, headphone jack',
                        'Color: Midnight' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Mantap',
                'Redesign terbaru Macbook Air, lebih Modern dan Catchy',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air 13" M4',
                '30W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 3
    { 
        id: 3, kategori: 'Mac', name: 'Macbook Air 15" M4 (2024) - Sky Blue', specs: '16GB RAM, 256GB SSD', 
        price: 19899000, stock: 5, grade: 'Baru', sku: 'G7X23MLQ',  sold: 232,
        images: ['images/produk/id3_G7X23MLQ/1.jpg', 'images/produk/id3_G7X23MLQ/2.jpg', 'images/produk/id3_G7X23MLQ/3.jpg', 'images/produk/id3_G7X23MLQ/4.jpg', 'images/produk/id3_G7X23MLQ/5.jpg', 'images/produk/id3_G7X23MLQ/6.jpg', 'images/produk/id3_G7X23MLQ/7.jpg', 'images/produk/id3_G7X23MLQ/8.jpg'], 
        description: {
            intro: 'MacBook Air is the world’s most popular laptop for a reason’s. It delivers up to 18 hours of battery life. The M4 chip unlocks a whole new level of performance for work and play. And it now comes in a stunning Sky Blue color.',
            specs: ['Chip: Apple M4 (10-core CPU, 10-core GPU)', 
                    'Layar: 15.3-inch Liquid Retina display with True Tone',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Two Thunderbolt 4 ports, headphone jack',
                        'Color: Sky Blue' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Mantap',
                'Redesign terbaru Macbook Air, lebih Modern dan Catchy',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air 15" M4',
                '35W Dual USB-C Port Compact Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 4
    { 
        id: 4, kategori: 'Mac', name: 'Macbook Air 15" M4 (2024) - Midnight', specs: '16GB RAM, 256GB SSD', 
        price: 19899000, stock: 6, grade: 'Baru', sku: '9HFZ3Y2A',  sold: 263,
        images: ['images/produk/id4_9HFZ3Y2A/1.jpg', 'images/produk/id4_9HFZ3Y2A/2.jpg', 'images/produk/id4_9HFZ3Y2A/3.jpg', 'images/produk/id4_9HFZ3Y2A/4.jpg', 'images/produk/id4_9HFZ3Y2A/5.jpg', 'images/produk/id4_9HFZ3Y2A/6.jpg', 'images/produk/id4_9HFZ3Y2A/7.jpg', 'images/produk/id4_9HFZ3Y2A/8.jpg'], 
        description: {
            intro: 'MacBook Air is the world’s most popular laptop for a reason’s. It delivers up to 18 hours of battery life. The M4 chip unlocks a whole new level of performance for work and play. And it now comes in a stunning Sky Blue color.',
            specs: ['Chip: Apple M4 (10-core CPU, 10-core GPU)', 
                    'Layar: 15.3-inch Liquid Retina display with True Tone',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Two Thunderbolt 4 ports, headphone jack',
                        'Color: Midnight' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Mantap',
                'Redesign terbaru Macbook Air, lebih Modern dan Catchy',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air 15" M4',
                '35W Dual USB-C Port Compact Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 5
    { 
        id: 5, kategori: 'Mac', name: 'Macbook Pro 14" M4 (2024) - Space Black', specs: '16GB RAM, 512GB SSD', 
        price: 23999000, stock: 2, grade: 'Baru', sku: 'W1B8PZ6K', sold: 112,
        images: ['images/produk/id5_W1B8PZ6K/1.jpg', 'images/produk/id5_W1B8PZ6K/2.jpg', 'images/produk/id5_W1B8PZ6K/3.jpg', 'images/produk/id5_W1B8PZ6K/4.jpg', 'images/produk/id5_W1B8PZ6K/5.jpg', 'images/produk/id5_W1B8PZ6K/6.jpg', 'images/produk/id5_W1B8PZ6K/7.jpg', 'images/produk/id5_W1B8PZ6K/8.jpg'], 
        description: {
            intro: 'MacBook Pro features the most advanced lineup of chips ever built for a pro laptop. Phenomenal single- and multithreaded CPU performance, faster unified memory, enhanced machine learning accelerators — the M4 family of chips gives you the kind of speed and capability you’ve never thought possible.',
            specs: ['Chip: Apple M4 (10-core CPU, 10-core GPU, 16-core Neural Engine)', 
                    'Layar: 14-inch Liquid Retina XDR display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Three Thunderbolt 4 ports, HDMI port, SDXC card slot, headphone jack',
                        'Color: Space Black' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Terbaik di Laptop Manapun',
                'Redesign terbaru Macbook Pro, lebih Modern',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        inTheBox: ['Unit MacBook Pro 14" M4',
                '70W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 6
    { 
        id: 6, kategori: 'Mac', name: 'Macbook Pro 14" M4 Pro (2024) - Space Black', specs: '24GB RAM, 512GB SSD', 
        price: 30799000, stock: 7, grade: 'Baru', sku: 'YZ93LMX4',  sold: 153,
        images: ['images/produk/id6_YZ93LMX4/1.jpg', 'images/produk/id6_YZ93LMX4/2.jpg', 'images/produk/id6_YZ93LMX4/3.jpg', 'images/produk/id6_YZ93LMX4/4.jpg', 'images/produk/id6_YZ93LMX4/5.jpg', 'images/produk/id6_YZ93LMX4/6.jpg', 'images/produk/id6_YZ93LMX4/7.jpg', 'images/produk/id6_YZ93LMX4/8.jpg'], 
        description: {
            intro: 'MacBook Pro features the most advanced lineup of chips ever built for a pro laptop. Phenomenal single- and multithreaded CPU performance, faster unified memory, enhanced machine learning accelerators — the M4 family of chips gives you the kind of speed and capability you’ve never thought possible.',
            specs: ['Chip: Apple M4 Pro (12‑core CPU, 16‑core GPU, 16‑core Neural Engine)', 
                    'Layar: 14-inch Liquid Retina XDR display',
                    'Memori: 24GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Three Thunderbolt 5 ports, HDMI port, SDXC card slot, headphone jack',
                        'Color: Space Black' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Transfer Data Super Cepat dengan Port Thunderbolt 5 (120Gb/s)',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Terbaik di Laptop Manapun',
                'Redesign terbaru Macbook Pro, lebih Modern',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        inTheBox: ['Unit MacBook Pro 14" M4 Pro',
                '70W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 7
    { 
        id: 7, kategori: 'Mac', name: 'Macbook Pro 14" M4 Max (2024) - Space Black', specs: '36GB RAM, 1TB SSD', 
        price: 48999000, stock: 6, grade: 'Baru', sku: 'KQ7AZ813',  sold: 112,
        images: ['images/produk/id7_KQ7AZ813/1.jpg', 'images/produk/id7_KQ7AZ813/2.jpg', 'images/produk/id7_KQ7AZ813/3.jpg', 'images/produk/id7_KQ7AZ813/4.jpg', 'images/produk/id7_KQ7AZ813/5.jpg', 'images/produk/id7_KQ7AZ813/6.jpg', 'images/produk/id7_KQ7AZ813/7.jpg', 'images/produk/id7_KQ7AZ813/8.jpg'], 
        description: {
            intro: 'MacBook Pro features the most advanced lineup of chips ever built for a pro laptop. Phenomenal single- and multithreaded CPU performance, faster unified memory, enhanced machine learning accelerators — the M4 family of chips gives you the kind of speed and capability you’ve never thought possible.',
            specs: ['Chip: Apple M4 Max (14‑core CPU, 32‑core GPU, 16‑core Neural Engine)', 
                    'Layar: 14-inch Liquid Retina XDR display',
                    'Memori: 36GB RAM terpadu', 
                    'Penyimpanan: 1TB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Three Thunderbolt 5 ports, HDMI port, SDXC card slot, headphone jack',
                        'Color: Space Black' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Transfer Data Super Cepat dengan Port Thunderbolt 5 (120Gb/s)',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Terbaik di Laptop Manapun',
                'Redesign terbaru Macbook Pro, lebih Modern',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        inTheBox: ['Unit MacBook Pro 14" M4 Max',
                '96W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 8
    { 
        id: 8, kategori: 'Mac', name: 'Macbook Pro 16" M4 Pro (2024) - Space Black', specs: '24GB RAM, 512GB SSD', 
        price: 39999000, stock: 7, grade: 'Baru', sku: '6NVB4XPQ',  sold: 201,
        images: ['images/produk/id8_6NVB4XPQ/1.jpg', 'images/produk/id8_6NVB4XPQ/2.jpg', 'images/produk/id8_6NVB4XPQ/3.jpg', 'images/produk/id8_6NVB4XPQ/4.jpg', 'images/produk/id8_6NVB4XPQ/5.jpg', 'images/produk/id8_6NVB4XPQ/6.jpg', 'images/produk/id8_6NVB4XPQ/7.jpg', 'images/produk/id8_6NVB4XPQ/8.jpg'], 
        description: {
            intro: 'MacBook Pro features the most advanced lineup of chips ever built for a pro laptop. Phenomenal single- and multithreaded CPU performance, faster unified memory, enhanced machine learning accelerators — the M4 family of chips gives you the kind of speed and capability you’ve never thought possible.',
            specs: ['Chip: Apple M4 Pro (14‑core CPU, 20‑core GPU, 16‑core Neural Engine)', 
                    'Layar: 16-inch Liquid Retina XDR display',
                    'Memori: 24GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Three Thunderbolt 5 ports, HDMI port, SDXC card slot, headphone jack',
                        'Color: Space Black' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Transfer Data Super Cepat dengan Port Thunderbolt 5 (120Gb/s)',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Terbaik di Laptop Manapun',
                'Redesign terbaru Macbook Pro, lebih Modern',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        inTheBox: ['Unit MacBook Pro 16" M4 Pro',
                '140W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 9
    { 
        id: 9, kategori: 'Mac', name: 'Macbook Pro 16" M4 Max (2024) - Space Black', specs: '36GB RAM, 1TB SSD', 
        price: 54999000, stock: 4, grade: 'Baru', sku: 'M29XQY8L',  sold: 142,
        images: ['images/produk/id9_M29XQY8L/1.jpg', 'images/produk/id9_M29XQY8L/2.jpg', 'images/produk/id9_M29XQY8L/3.jpg', 'images/produk/id9_M29XQY8L/4.jpg', 'images/produk/id9_M29XQY8L/5.jpg', 'images/produk/id9_M29XQY8L/6.jpg', 'images/produk/id9_M29XQY8L/7.jpg', 'images/produk/id9_M29XQY8L/8.jpg'], 
        description: {
            intro: 'MacBook Pro features the most advanced lineup of chips ever built for a pro laptop. Phenomenal single- and multithreaded CPU performance, faster unified memory, enhanced machine learning accelerators — the M4 family of chips gives you the kind of speed and capability you’ve never thought possible.',
            specs: ['Chip: Apple M4 Max (14‑core CPU, 32‑core GPU, 16‑core Neural Engine)', 
                    'Layar: 16-inch Liquid Retina XDR display',
                    'Memori: 36GB RAM terpadu', 
                    'Penyimpanan: 1TB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Three Thunderbolt 5 ports, HDMI port, SDXC card slot, headphone jack',
                        'Color: Space Black' ]
        },
        pros: ['Semua Produk Baru Bergaransi iBox Official',
                'Transfer Data Super Cepat dengan Port Thunderbolt 5 (120Gb/s)',
                'Processor Super Kencang Anti Panas',
                'Speaker dan Bass Terbaik di Laptop Manapun',
                'Redesign terbaru Macbook Pro, lebih Modern',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        inTheBox: ['Unit MacBook Pro 16" M4 Max',
                '140W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 10
    { 
        id: 10, kategori: 'Mac', name: 'Macbook Air 13" M3 (2023) - Space Grey', specs: '16GB RAM, 256GB SSD', 
        price: 14299000, stock: 11, grade: 'Baru', sku: 'AXZL5NQ7',  sold: 117,
        images: ['images/produk/id10_AXZL5NQ7/1.jpg', 'images/produk/id10_AXZL5NQ7/2.jpg', 'images/produk/id10_AXZL5NQ7/3.jpg', 'images/produk/id10_AXZL5NQ7/4.jpg'], 
        description: {
            intro: 'MacBook Air is the world’s most popular laptop for a reason’s. It delivers up to 18 hours of battery life. The M3 chip unlocks a whole new level of performance for work and play.',
            specs: ['Chip: Apple M3 (8-core CPU, 8-core GPU)', 
                    'Layar: 13.6-inch Liquid Retina display with True Tone',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                    'Camera: 12MP Center Stage camera',
                    'Charging: MagSafe 3 charging port',
                    'Port: Two Thunderbolt 4 ports, headphone jack',
                        'Color: Space Grey' ]
        },
        pros: ['Processor Super Kencang Anti Panas',
                'Speaker dan Bass Mantap',
                'Redesign terbaru Macbook Air, lebih Modern dan Catchy',
                'Baterai tahan sangat lama',
                'Charging Menggunakan Magsafe'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air 13" M3',
                '30W USB-C Power Adapter',
                'Magsafe Charge Cable (2m)']
    },
    // Produk 11
    { 
        id: 11, kategori: 'Mac', name: 'Macbook Pro 15" Intel Core i7 (2016) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 5600000, stock: 3, grade: 'A', sku: '7CCF0VDG',  sold: 72,
        images: ['images/produk/id11_7CCF0VDG/1.jpg', 'images/produk/id11_7CCF0VDG/2.jpg', 'images/produk/id11_7CCF0VDG/3.jpg', 'images/produk/id11_7CCF0VDG/4.jpg', 'images/produk/id11_7CCF0VDG/5.jpg', 'images/produk/id11_7CCF0VDG/6.jpg', 'images/produk/id11_7CCF0VDG/7.jpg'], 
        description: {
            intro: 'MacBook Pro ini adalah pilihan tepat bagi Anda yang mencari laptop bertenaga dengan harga terjangkau. Dapur pacunya menggunakan prosesor Intel Core i7 yang terbukti andal untuk berbagai tugas berat. Kondisinya pun sangat istimewa dengan fisik 95% mulus dan kesehatan baterai terjaga di atas 90%.',
            specs: ['Chip: Intel Core i7 @2.7Ghz', 
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                    'Layar: 13.3-inch Retina display',
                    'CC: 203',
                    'BH: Normal',
                    'Color: Space Grey' ]
        },
        pros: ['Design lebih modern dibanding versi 2015',
                'Layar Jernih tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Dilengkapi Touchbar untuk kemudahan Navigasi'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
                
        inTheBox: ['Unit Macbook Pro i7',
                   'Charger Original',
                   'USB-C Charge Cable (2m)',
                   'Kotak Original (jika tersedia)']
    },
    // Produk 12
    { 
        id: 12, kategori: 'Mac', name: 'Macbook Air 13" M1 (2020) - RoseGold', specs: '8GB RAM, 256GB SSD', 
        price: 8100000, stock: 6, grade: 'A', sku: '7CLL02GD',  sold: 32,
        images: ['images/produk/id12_7CLL02GD/1.jpg', 'images/produk/id12_7CLL02GD/2.jpg', 'images/produk/id12_7CLL02GD/3.jpg', 'images/produk/id12_7CLL02GD/4.jpg', 'images/produk/id12_7CLL02GD/5.jpg', 'images/produk/id12_7CLL02GD/6.jpg', 'images/produk/id12_7CLL02GD/7.jpg'], 
        description: {
            intro: 'Rasakan revolusi performa dengan MacBook Air M1 (2020). Chip M1 super cepat ini menawarkan kinerja luar biasa dan daya tahan baterai hingga 18 jam, semua dalam desain tipis yang senyap tanpa kipas. Unit ini dalam kondisi istimewa dengan fisik 95% mulus dan Battery Health 100% (CC rendah: 69), siap menjadi andalan Anda untuk produktivitas di mana saja.',
            specs: ['Chip: Apple M1 (8-core CPU, 7-core GPU)', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                    'CC: 69',
                    'BH: 100%',
                    'Color: RoseGold' ]
        },
        pros: ['Processor Apple, Kenceng dan Anti Panas',
                'Dilengkapi TouchID untuk kemudahan Login',
                'Speaker Terbaik di Laptop Tipis',
                'Design Modern Unibody dan Sangat Tipis',
                'Kamera jernih dan bagus',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Build Quality sangat Kokoh',
                'Jack Audio dan Thunderbolt 3'],
        cons: ['Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Air M1',
                'Charger Original',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 13
    { 
        id: 13, kategori: 'Mac', name: 'Macbook Pro 13" M1 (2020) - Space Grey', specs: '8GB RAM, 256GB SSD', 
        price: 9000000, stock: 4, grade: 'A', sku: '7RCF3DWH',  sold: 58,
        images: ['images/produk/id13_7RCF3DWH/1.jpg', 'images/produk/id13_7RCF3DWH/2.jpg', 'images/produk/id13_7RCF3DWH/3.jpg', 'images/produk/id13_7RCF3DWH/4.jpg', 'images/produk/id13_7RCF3DWH/5.jpg', 'images/produk/id13_7RCF3DWH/6.jpg', 'images/produk/id13_7RCF3DWH/7.jpg'], 
        description: {
            intro: 'Pilihan tepat untuk mendapatkan performa level Pro dalam kondisi istimewa. Berbeda dari MacBook Air, model Pro ini dilengkapi kipas pendingin untuk menjaga performa puncak tetap konsisten dan Touch Bar untuk alur kerja yang lebih efisien. Kondisi fisik produk 95% mulus dan yang terpenting, dibekali baterai baru (CC: 13), memberikan Anda performa dan daya tahan yang terasa seperti baru.',
            specs: ['Chip: Apple M1 (8-core CPU, 7-core GPU)', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 13',
                        'BH: 100%',
                        'Color: Space Grey' ]
        },
        pros: ['Prosesor Super Kencang Anti Panas',
                'Layar Jernih tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Dilengkapi Touchbar untuk kemudahan Navigasi',
                'Dilengkapi kipas untuk menjaga suhu laptop(tidak seperti macbook air yang fanless)',
                'Baterai tahan sangat lama (diatas 10 jam pemakaian ringan)'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Pro M1',
                'Charger Original',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 14
    { 
        id: 14, kategori: 'Mac', name: 'MacBook Air 13" M1 (2020) - Space Grey', specs: '8GB RAM, 256GB SSD', 
        price: 8000000, stock: 5, grade: 'A', sku: '7CLL1HBK',  sold: 80,
        images: ['images/produk/id14_7CLL1HBK/1.jpg', 'images/produk/id14_7CLL1HBK/2.jpg', 'images/produk/id14_7CLL1HBK/3.jpg', 'images/produk/id14_7CLL1HBK/4.jpg', 'images/produk/id14_7CLL1HBK/5.jpg', 'images/produk/id14_7CLL1HBK/6.jpg'], 
        description: {
            intro: 'Pilihan cerdas untuk performa dan portabilitas. MacBook Air M1 ini memiliki kondisi fisik 95% mulus dan kesehatan baterai 94%. Dengan harga terjangkau, Anda mendapatkan perangkat andal untuk segala kebutuhan, dari bekerja hingga hiburan, tanpa kompromi pada kualitas.',
            specs: ['Chip: Apple M1 (8-core CPU, 7-core GPU)', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 178',
                        'BH: 94%',
                        'Color: Space Grey' ]
        },
        pros: ['Processor Kenceng dan Anti Panas',
                'Speaker Top Quality',
                'Design Modern Unibody dan Sangat Tipis',
                'Kamera jernih dan bagus',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Build Quality sangat Kokoh',
                'Dilengkapi TouchID untuk kemudahan Login'],
        cons: ['Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Air M1',
                'Charger Original',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 15
    { 
        id: 15, kategori: 'Mac', name: '15MacBook Pro 13" Intel Core i7 (2018) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 5750000, stock: 3, grade: 'A', sku: 'OMOTA0GR',  sold: 41,
        images: ['images/produk/id15_OMOTA0GR/1.jpg', 'images/produk/id15_OMOTA0GR/2.jpg', 'images/produk/id15_OMOTA0GR/3.jpg', 'images/produk/id15_OMOTA0GR/4.jpg', 'images/produk/id15_OMOTA0GR/5.jpg'], 
        description: {
            intro: 'Dapatkan MacBook Pro 15-inch spek tinggi dengan kondisi istimewa. Performa andal dari Intel i7, RAM 16GB, dan SSD 512GB. Fisik 95% mulus, lengkap dengan Touch Bar, dan baterai prima. Pilihan hemat untuk tenaga komputasi level profesional.',
            specs: ['Chip: Intel Core i7', 
                    'Layar: 15-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 131',
                        'BH: Normal',
                        'Color: Space Grey' ]
        },
        pros: ['Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Dilengkapi TouchBar untuk kemudahan navigasi',
                'Dilengkapi TouchID untuk kemudahan login',
                'Baterai tahan lama',
                'Kamera jernih dan bagus'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Pro',
                'Charger Original',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 16
    { 
        id: 16, kategori: 'Mac', name: 'Macbook Pro 13" Intel Core i5 (2019) - Space Grey', specs: '8GB RAM, 256GB SSD', 
        price: 6300000, stock: 6, grade: 'A', sku: '7CTH4QBL',  sold: 29,
        images: ['images/produk/id16_7CTH4QBL/1.jpg', 'images/produk/id16_7CTH4QBL/2.jpg', 'images/produk/id16_7CTH4QBL/3.jpg', 'images/produk/id16_7CTH4QBL/4.jpg', 'images/produk/id16_7CTH4QBL/5.jpg', 'images/produk/id16_7CTH4QBL/6.jpg', 'images/produk/id16_7CTH4QBL/7.jpg'], 
        description: {
            intro: 'Dapatkan MacBook Pro 2019 dengan kondisi istimewa seperti baru. Fisik sangat terawat 95% mulus, dan baterai dalam kondisi sempurna di 100% (CC rendah: 98). Nilai terbaik untuk Anda yang mencari laptop Apple andal dengan performa Intel i5 untuk aktivitas harian.',
            specs: ['Chip: Intel Core i5 1.4Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 98',
                        'BH: 100%',
                        'Color: Space Grey' ]
        },
        pros: ['Dilengkapi TouchID untuk kemudahan login',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Kamera jernih dan bagus',
                'Build Quality sangat Kokoh'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Pro',
                'Charger Original',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 17
    { 
        id: 17, kategori: 'Mac', name: 'Macbook Pro 14" M1 Pro (2021) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 15300000, stock: 4, grade: 'A', sku: '7RHAEOWD',  sold: 65,
        images: ['images/produk/id17_7RHAEOWD/1.jpg', 'images/produk/id17_7RHAEOWD/2.jpg', 'images/produk/id17_7RHAEOWD/3.jpg', 'images/produk/id17_7RHAEOWD/4.jpg', 'images/produk/id17_7RHAEOWD/5.jpg', 'images/produk/id17_7RHAEOWD/6.jpg', 'images/produk/id17_7RHAEOWD/7.jpg'], 
        description: {
            intro: 'Kesempatan langka: MacBook Pro 14" M1 Pro dalam kondisi sempurna. Fisik 100% mulus, baterai 100% (CC 11), seperti membuka unit baru. Nilai tak terkalahkan untuk performa profesional, layar XDR 120Hz, dan port lengkap dengan harga jauh lebih hemat.',
            specs: ['Chip: Apple M1 Pro (8-core CPU, 14-core GPU)', 
                    'Layar: 14-inch 120 Hz Mini-LED Retina XDR Display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 11',
                        'BH: 100%',
                        'Color: Space Grey' ]
        },
        pros: ['Procesor Super Kencang dan Hemat Daya',
                'Dilengkapi TouchID untuk kemudahan login',
                'Layar 120Hz Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 100% mulus',
                'Speaker Normal dan Bass Mantap',
                'Kamera jernih dan bagus',
                'Build Quality sangat Kokoh',
                'Sudah menggunakan Magsafe',
                'Sudah dilengkapi HDMI dan Slot SD Card'],
        
        inTheBox: ['Unit MacBook Pro 14"',
                '70w USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 18
    { 
        id: 18, kategori: 'Mac', name: 'MacBook Air 13" M1 (2020) - Space Grey', specs: '8GB RAM, 256GB SSD', 
        price: 7800000, stock: 2, grade: 'B', sku: 'OMHA9TBL',  sold: 47,
        images: ['images/produk/id18_OMHA9TBL/1.jpg', 'images/produk/id18_OMHA9TBL/2.jpg', 'images/produk/id18_OMHA9TBL/3.jpg', 'images/produk/id18_OMHA9TBL/4.jpg', 'images/produk/id18_OMHA9TBL/5.jpg', 'images/produk/id18_OMHA9TBL/6.jpg', 'images/produk/id18_OMHA9TBL/7.jpg', ], 
        description: {
            intro: 'Pilihan hemat untuk performa M1 yang fenomenal. MacBook Air ini dalam kondisi baik (fisik 90% mulus) dan baterai sangat sehat di 95%. Nikmati kecepatan, desain tipis, dan ketahanan baterai hingga 16 jam. Nilai terbaik untuk menunjang semua aktivitas Anda.',
            specs: ['Chip: Apple M1 (8-core CPU, 7-core GPU)', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 152',
                        'BH: 95%',
                        'Color: Space Grey' ]
        },
        pros: ['Processor Super Cepat dan Hemat Daya',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Speaker Normal dan Bass Mantap',
                'Dilengkapi TouchID untuk kemudahan login',
                'Kamera jernih dan bagus',
                'Build Quality sangat Kokoh',
                'Kondisi fisik 90% mulus',
                'Design Modern dan Super Tipis',
                'Baterai Bertahan Sangat Lama Hingga 16 Jam'],
        cons: ['Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Air M1',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 19
    { 
        id: 19, kategori: 'Mac', name: 'Macbook Pro 13" Intel Core i5 (2018) - Space Grey', specs: '8GB RAM, 256GB SSD', 
        price: 6400000, stock: 3, grade: 'A', sku: '7RLLD8WO',  sold: 37,
        images: ['images/produk/id19_7RLLD8WO/1.jpg', 'images/produk/id19_7RLLD8WO/2.jpg', 'images/produk/id19_7RLLD8WO/3.jpg', 'images/produk/id19_7RLLD8WO/4.jpg', 'images/produk/id19_7RLLD8WO/5.jpg', 'images/produk/id19_7RLLD8WO/6.jpg'], 
        description: {
            intro: 'Pilihan cerdas untuk merasakan pengalaman Pro. MacBook Pro 2018 ini dilengkapi Touch Bar dan ditenagai Intel i5. Kondisinya istimewa dengan fisik 95% mulus dan kesehatan baterai 93%. Performa dan fitur premium dalam satu paket bernilai tinggi.',
            specs: ['Chip: Intel Core i5 @2.3Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 158',
                        'BH: 93%',
                        'Color: Space Grey' ]
        },
        pros: ['Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Jack Audio dan Thunderbolt 3',
                'Design Modern Unibody',
                'Kamera jernih dan bagus',
                'Speaker Top, Bass Mantap',
                'Kondisi fisik 95% mulus',
                'Build Quality sangat Kokoh',
                'Dilengkapi TouchBar dan TouchID'],
        cons: ['Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Pro 2018',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 20
    { 
        id: 20, kategori: 'Mac', name: 'MacBook Air 13" M1 (2020) - RoseGold', specs: '8GB RAM, 256GB SSD', 
        price: 8250000, stock: 5, grade: 'A', sku: '7CHKJ1TP',  sold: 76,
        images: ['images/produk/id20_7CHKJ1TP/1.jpg', 'images/produk/id20_7CHKJ1TP/2.jpg', 'images/produk/id20_7CHKJ1TP/3.jpg', 'images/produk/id20_7CHKJ1TP/4.jpg', 'images/produk/id20_7CHKJ1TP/5.jpg', 'images/produk/id20_7CHKJ1TP/6.jpg', 'images/produk/id20_7CHKJ1TP/7.jpg', 'images/produk/id20_7CHKJ1TP/8.jpg'], 
        description: {
            intro: 'Dapatkan MacBook Air M1 RoseGold dalam kondisi mendekati baru. Fisik terawat 95% mulus dengan kesehatan baterai istimewa 99% (CC sangat rendah: 69). Nilai terbaik untuk performa M1 yang cepat dan sunyi, ideal untuk menunjang gaya hidup dinamis Anda.',
            specs: ['Chip: Apple M1 (8-core CPU, 7-core GPU)', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 69',
                        'BH: 99%',
                        'Color: RoseGold' ]
        },
        pros: ['Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Dilengkapi TouchID untuk kemudahan login',
                'Baterai tahan lama',
                'Kamera jernih dan bagus',
                'Bobot ringan dan kokoh'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air M1',
                '30W USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 21
    { 
        id: 21, kategori: 'Mac', name: 'Macbook Pro 15" Intel Core i7 (2018) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 6300000, stock: 2, grade: 'A', sku: 'OMHZR7YL',  sold: 59,
        images: ['images/produk/id21_OMHZR7YL/1.jpg', 'images/produk/id21_OMHZR7YL/2.jpg', 'images/produk/id21_OMHZR7YL/3.jpg', 'images/produk/id21_OMHZR7YL/4.jpg', 'images/produk/id21_OMHZR7YL/5.jpg'], 
        description: {
            intro: 'Nilai tinggi untuk profesional. MacBook Pro 15-inch ini ditenagai Intel i7, RAM 16GB, dan SSD 512GB untuk tugas berat. Kondisi istimewa dengan fisik 95% mulus dan kesehatan baterai 97%. Dapatkan performa Pro sejati dengan harga yang sangat cerdas.',
            specs: ['Chip: Intel Core i7 @2.2Ghz', 
                    'Layar: 15-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 152',
                        'BH: 97%',
                        'Color: Space Grey' ]
        },
        pros: ['Dilengkapi Touch Bar untuk kemudahan Navigasi',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Speaker Normal dan Bass Mantap',
                'Design Modern',
                'Dilengkapi TouchID untuk kemudahan login',
                'Kamera jernih dan bagus',
                '4x Thunderbolt 3',
                'Build Quality sangat Kokoh',
                'Kondisi fisik 95% mulus'],
        cons: ['Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Pro',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 22
    { 
        id: 22, kategori: 'Mac', name: 'Macbook Pro 15" Intel Core i7 (2018) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 6600000, stock: 4, grade: 'A', sku: '7RHADMTP',  sold: 28,
        images: ['images/produk/id22_7RHADMTP/1.jpg', 'images/produk/id22_7RHADMTP/2.jpg', 'images/produk/id22_7RHADMTP/3.jpg', 'images/produk/id22_7RHADMTP/4.jpg', 'images/produk/id22_7RHADMTP/5.jpg', 'images/produk/id22_7RHADMTP/6.jpg', 'images/produk/id22_7RHADMTP/7.jpg'], 
        description: {
            intro: 'Performa tinggi, harga menarik. MacBook Pro 15-inch ini siap bekerja keras dengan Intel i7, RAM 16GB, dan SSD 512GB. Kondisinya istimewa, fisik 95% mulus dan baterai sangat sehat di 95%. Nilai sempurna untuk profesional yang butuh keandalan.',
            specs: ['Chip: Intel Core i7 @2.5Ghz', 
                    'Layar: 15-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 145',
                        'BH: 95%',
                        'Color: Space Grey' ]
        },
        pros: ['Dilengkapi TouchID untuk kemudahan login',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Kamera jernih dan bagus',
                'Build Quality sangat Kokoh'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)', 
                'Bobot Laptop Relatif Berat'],
        inTheBox: ['Unit MacBook Pro 2018',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 23
    { 
        id: 23, kategori: 'Mac', name: 'Macbook Pro 13" Intel Core i7 (2015) - Silver', specs: '8GB RAM, 512GB SSD', 
        price: 5200000, stock: 0, grade: 'B', sku: '7ROT12BK', sold: 84,
        images: ['images/produk/id23_7ROT12BK/1.jpg', 'images/produk/id23_7ROT12BK/2.jpg', 'images/produk/id23_7ROT12BK/3.jpg', 'images/produk/id23_7ROT12BK/4.jpg', 'images/produk/id23_7ROT12BK/5.jpg', 'images/produk/id23_7ROT12BK/6.jpg', 'images/produk/id23_7ROT12BK/7.jpg', 'images/produk/id23_7ROT12BK/8.jpg'], 
        description: {
            intro: 'MacBook Pro 2015, sebuah workhorse andal dengan spek upgrade Core i7 dan SSD 512GB. Baterai sangat sehat (CC 69) siap untuk kerja panjang. Ada dent kecil wajar pemakaian, namun performanya menawarkan nilai terbaik di kelasnya. Pilihan hemat dan bertenaga.',
            specs: ['Chip: Intel Core i7 @3.1Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 69',
                        'BH: Normal',
                        'Color: Silver' ]
        },
        pros: ['Layar jernih tanpa whitespot/deadpixel',
                'Kondisi fisik 90% mulus',
                'Speaker normal dan bass mantap'],
        cons: ['Dent-dent kecil dan Minor'],
        inTheBox: ['Unit MacBook Pro 2015',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 24
    { 
        id: 24, kategori: 'Mac', name: 'Macbook Pro 15" Intel Core i7 (2017) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 5100000, stock: 3, grade: 'A', sku: '7RCF3EBK',  sold: 34,
        images: ['images/produk/id24_7RCF3EBK/1.jpg', 'images/produk/id24_7RCF3EBK/2.jpg', 'images/produk/id24_7RCF3EBK/3.jpg', 'images/produk/id24_7RCF3EBK/4.jpg', 'images/produk/id24_7RCF3EBK/5.jpg'], 
        description: {
            intro: 'Sebuah powerhouse sejati. MacBook Pro 15" ini punya spek monster: Core i7, RAM 16GB, SSD 512GB, dan Dual VGA (AMD). Kondisi fisik 90% mulus dengan baterai yang sangat awet untuk kerja berat. Nilai terbaik untuk performa grafis dan komputasi profesional.',
            specs: ['Chip: Intel Core i7 @3.1Ghz',
                    'Graphic Card: Dual VGA (intel HD & AMD)',
                    'Layar: 15-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 370',
                        'BH: Normal',
                        'Color: Space Grey']
        },
        pros: ['Dilengkapi Touchbar untuk kemudahan navigasi',
                'Layar Jernih tanpa whitespot/deadpixel',
                'Kondisi fisik 90% mulus',
                'Speaker Sangat Bagus',
                'Backlit Keyboard',
                'Baterai Sangat awet walau pemakaian berat'],
        cons: ['Bobot Laptop mencapai 2kg'],
        inTheBox: ['Unit MacBook Pro 2017',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 25
    { 
        id: 25, kategori: 'Mac', name: 'Macbook Air 13" Intel Core i5 (2019) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 5200000, stock: 3, grade: 'A', sku: '7RHX3GBK',  sold: 69,
        images: ['images/produk/id25_7RHX3GBK/1.jpg', 'images/produk/id25_7RHX3GBK/2.jpg', 'images/produk/id25_7RHX3GBK/3.jpg', 'images/produk/id25_7RHX3GBK/4.jpg', 'images/produk/id25_7RHX3GBK/5.jpg', 'images/produk/id25_7RHX3GBK/6.jpg'], 
        description: {
            intro: 'Nilai tak terkalahkan untuk MacBook Air 2019. Unit ini punya RAM 16GB dan SSD 512GB, jauh di atas standar. Kondisi fisik 95% mulus dan baterai 92% sangat prima. Pilihan sempurna untuk yang butuh kecepatan dan kapasitas ekstra.',
            specs: ['Chip: Intel Core i5 @1.4Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 288',
                        'BH: 92%',
                        'Color: Space Grey' ]
        },
        pros: ['Dilengkapi TouchID untuk kemudahan login',
                'Layar jernih, terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker normal dan bass mantap',
                'Kamera jernih dan bagus',
                'Build quality sangat kokoh',
                'Desain modern dan super tipis',],
        cons: ['Performa Kurang bagi yang suka game AAA atau Render berat', 
                'Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Air 2019',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 26
    { 
        id: 26, kategori: 'Mac', name: 'Macbook Pro 15" Intel Core i7 (2018) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 6900000, stock: 4, grade: 'A', sku: 'OMHZR7BR',  sold: 53,
        images: ['images/produk/id26_OMHZR7BR/1.jpg', 'images/produk/id26_OMHZR7BR/2.jpg', 'images/produk/id26_OMHZR7BR/3.jpg', 'images/produk/id26_OMHZR7BR/4.jpg', 'images/produk/id26_OMHZR7BR/5.jpg', 'images/produk/id26_OMHZR7BR/6.jpg', 'images/produk/id26_OMHZR7BR/7.jpg'], 
        description: {
            intro: 'Kekuatan Pro untuk profesional. MacBook Pro 15-inch ini dibekali spek tinggi (i7/16GB/512GB) untuk performa maksimal. Kondisi fisik 90% mulus dengan kesehatan baterai sangat prima di 92%. Nilai terbaik untuk menaklukkan semua pekerjaan berat Anda dengan andal.',
            specs: ['Chip: Intel Core i7 @2.6Ghz', 
                    'Layar: 15-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 232',
                        'BH: 92%',
                        'Color: Space Grey' ]
        },
        pros: ['4x Thunderbolt 3',
                'Layar jernih, terang dan tanpa whitespot/deadpixel',
                'Speaker normal dan bass mantap',
                'Dilengkapi TouchID untuk kemudahan login',
                'Dilengkapi Touch Bar untuk kemudahan navigasi',
                'Kamera jernih dan bagus',
                'Build quality sangat kokoh',
                'Kondisi fisik 90% mulus',
                'Desain modern'],
        cons: ['Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Pro 2018',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 27
    { 
        id: 27, kategori: 'Mac', name: 'Macbook Air 13" Intel Core i3 (2020) - Space Grey', specs: '8GB RAM, 256GB SSD', 
        price: 6300000, stock: 4, grade: 'A', sku: '7RCF3DBK',  sold: 62,
        images: ['images/produk/id27_7RCF3DBK/1.jpg', 'images/produk/id27_7RCF3DBK/2.jpg', 'images/produk/id27_7RCF3DBK/3.jpg', 'images/produk/id27_7RCF3DBK/4.jpg', 'images/produk/id27_7RCF3DBK/5.jpg', 'images/produk/id27_7RCF3DBK/6.jpg'], 
        description: {
            intro: 'Nilai terbaik untuk MacBook Air 2020. Dengan kondisi fisik 95% mulus dan baterai sehat 89%, laptop ini menawarkan performa kencang untuk harganya. Sangat ideal dan hemat untuk mahasiswa atau pekerjaan ringan sehari-hari. Desain tipis, ringan, dan modern.',
            specs: ['Chip: Intel Core i3 @1,1Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 220',
                        'BH: 89%',
                        'Color: Space Grey' ]
        },
        pros: ['Layar Jernih tanpa whitespot/deadpixel',
                'Performa sangat kencang untuk harganya',
                'Kondisi fisik 95% mulus',
                'Speaker Mantap',
                'Tipis, ringan, dan mudah dibawa'],
        cons: ['Bukan laptop terbaik untuk pekerjaan berat'],
        inTheBox: ['Unit MacBook Air 2020',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 28
    { 
        id: 28, kategori: 'Mac', name: 'Macbook Pro 15" Intel Core i7 (2019) - Space Grey', specs: '16GB RAM, 512GB SSD', 
        price: 7300000, stock: 5, grade: 'A', sku: '7CHKCYBK',  sold: 45,
        images: ['images/produk/id28_7CHKCYBK/1.jpg', 'images/produk/id28_7CHKCYBK/2.jpg', 'images/produk/id28_7CHKCYBK/3.jpg', 'images/produk/id28_7CHKCYBK/4.jpg', 'images/produk/id28_7CHKCYBK/5.jpg', 'images/produk/id28_7CHKCYBK/6.jpg'], 
        description: {
            intro: 'Powerhouse untuk para profesional. MacBook Pro 15-inch 2019 ini punya spek jawara: i7, 16GB RAM, 512GB SSD, dan grafis ganda AMD Radeon. Kondisi fisik 90% mulus dengan baterai 93% prima. Nilai sempurna untuk semua kebutuhan kreatif dan teknis Anda.',
            specs: ['Chip: Intel Core i7 @2.6Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 512GB SSD',
                        'CC: 264',
                        'BH: 93%',
                        'Color: Space Grey' ]
        },
        pros: ['Dilengkapi TouchBar untuk kemudahan navigasi',
                'Dilengkapi TouchID untuk kemudahan login',
                'Layar jernih, terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 90% mulus',
                'Speaker normal dan bass mantap',
                'Kamera jernih dan bagus',
                'Build quality sangat kokoh',
                'Desain modern dan tipis',
                'Dual VGA, Intel UHD dan AMD Radeon'],
        cons: ['Bobot kurang cocok bagi yang portabilitas tinggi', 
                'Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Pro 2019',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 29
    { 
        id: 29, kategori: 'Mac', name: 'Macbook Pro 13" Intel Core i5 (2017) - Silver', specs: '8GB RAM, 256GB SSD', 
        price: 4800000, stock: 0, grade: 'A', sku: 'OMHA44BK',  sold: 77,
        images: ['images/produk/id29_OMHA44BK/1.jpg', 'images/produk/id29_OMHA44BK/2.jpg', 'images/produk/id29_OMHA44BK/3.jpg', 'images/produk/id29_OMHA44BK/4.jpg', 'images/produk/id29_OMHA44BK/5.jpg', 'images/produk/id29_OMHA44BK/6.jpg'], 
        description: {
            intro: 'Kesempatan langka: MacBook Pro 2017 dengan kondisi baterai seperti baru (BH 99%, CC 122). Fisik sangat terawat 95% mulus. Ditenagai Intel i5, ini adalah nilai terbaik untuk mendapatkan laptop Pro yang andal dan awet dengan harga sangat terjangkau.',
            specs: ['Chip: Intel Core i5 @2.3Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 122',
                        'BH: 99%',
                        'Color: Silver' ]
        },
        pros: ['Speaker top quality',
                'Desain modern unibody',
                'Kamera jernih dan bagus',
                'Layar jernih, terang dan tanpa whitespot/deadpixel',
                'Build quality sangat kokoh',
                'Kondisi fisik 95% mulus',
                '2x Thunderbolt 3'],
        cons: ['Hanya ada USB Type-C (disarankan beli dongle)', 
                'Belum ada TouchID, tidak bisa login pakai sidik jari'],
        inTheBox: ['Unit MacBook Pro 2017',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 30
    { 
        id: 30, kategori: 'Mac', name: 'Macbook Pro 13" Intel Core i7 (2016) - Space Grey', specs: '16GB RAM, 256GB SSD', 
        price: 5100000, stock: 2, grade: 'A', sku: 'OMLL6QWT',  sold: 39,
        images: ['images/produk/id30_OMLL6QWT/1.jpg', 'images/produk/id30_OMLL6QWT/2.jpg', 'images/produk/id30_OMLL6QWT/3.jpg', 'images/produk/id30_OMLL6QWT/4.jpg', 'images/produk/id30_OMLL6QWT/5.jpg'], 
        description: {
            intro: 'Dapatkan performa Pro bertenaga dengan MacBook Pro 2016 (i7/16GB RAM). Kondisi istimewa, fisik 95% mulus dan baterai 95% prima. Pilihan cerdas untuk pekerjaan yang butuh kecepatan lebih tanpa menguras kantong. Kualitas dan keandalan terjamin.',
            specs: ['Chip: Intel Core i7 @2.2Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 16GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 184',
                        'BH: 95%',
                        'Color: Space Grey' ]
        },
        pros: ['Speaker sangat enak',
                'Desain modern unibody',
                'Kamera jernih dan bagus',
                'Layar jernih, terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Build quality sangat kokoh',
                'Jack audio dan Thunderbolt 3'],
        cons: ['Belum ada TouchBar dan TouchID', 
                'Hanya ada USB Type-C (disarankan beli dongle)'],
        inTheBox: ['Unit MacBook Pro 2016',
                '30W USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 31
    { 
        id: 31, kategori: 'Mac', name: 'Macbook Air 13" Intel Core i5 (2018) - RoseGold', specs: '8GB RAM, 256GB SSD', 
        price: 5750000, stock: 1, grade: 'A', sku: '7RHASNGR',  sold: 25,
        images: ['images/produk/id31_7RHASNGR/1.jpg', 'images/produk/id31_7RHASNGR/2.jpg', 'images/produk/id31_7RHASNGR/3.jpg', 'images/produk/id31_7RHASNGR/4.jpg', 'images/produk/id31_7RHASNGR/5.jpg', 'images/produk/id31_7RHASNGR/6.jpg', 'images/produk/id31_7RHASNGR/7.jpg'], 
        description: {
            intro: 'Seperti baru! MacBook Air 2018 Rose Gold dengan kondisi baterai sempurna 100% (CC sangat rendah: 53). Fisik 95% mulus, ditenagai Intel i5. Ini adalah nilai terbaik untuk mendapatkan laptop Apple yang terasa baru dengan daya tahan baterai maksimal.',
            specs: ['Chip: Intel Core i5 @1.6Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                       'CC: 53',
                        'BH: 100%',
                        'Color: RoseGold'  ]
        },
        pros: ['Dilengkapi TouchID untuk kemudahan login',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Kamera jernih dan bagus',
                'Bobot ringan dan kokoh'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air 2018',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 32
    { 
        id: 32, kategori: 'Mac', name: 'Macbook Air 13" Intel Core i5 (2017) - Silver', specs: '8GB RAM, 128GB SSD', 
        price: 2100000, stock: 0, grade: 'B', sku: '7RLLD8WH', sold: 22,
        images: ['images/produk/id32_7RLLD8WH/1.jpg', 'images/produk/id32_7RLLD8WH/2.jpg', 'images/produk/id32_7RLLD8WH/3.jpg', 'images/produk/id32_7RLLD8WH/4.jpg', 'images/produk/id32_7RLLD8WH/5.jpg'], 
        description: {
            intro: 'Pilihan paling terjangkau untuk masuk ke ekosistem Apple. MacBook Air 2017 ini ideal untuk tugas ringan, Browse, dan mengetik. Kondisi fisik 90% mulus (Grade B) dengan baterai normal. Sebuah laptop andal yang menawarkan nilai luar biasa dengan harga sangat hemat.',
            specs: ['Chip: Intel Core i5 @1.8Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 128GB SSD',
                        'CC: 312',
                        'BH: Normal',
                        'Color: Silver/White' ]
        },
        pros: ['Layar Jernih dan Terang',
                'Design Unibody',
                'Kamera bagus',
                'Charge menggunakan MagSafe',
                'Speaker Cukup Bagus',
                'Kondisi fisik 90% mulus',
                'Build Quality sangat Kokoh',
                'Cocok Untuk Pekerjaan dan Aktivitas Ringan'],
        cons: ['Belum Thunderbolt 3', 
                'Desain bezel layar yang agak tebal',
                'Belum Redesign ala-ala Macbook Terbaru'],
        inTheBox: ['Unit MacBook Air 2017',
                'Power Adapter',
                'Magsafe Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 33
    { 
        id: 33, kategori: 'Mac', name: 'Macbook Air 13" M2 (2022) - Silver', specs: '8GB RAM, 256GB SSD', 
        price: 11200000, stock: 4, grade: 'A', sku: 'L9CF01BK',  sold: 51,
        images: ['images/produk/id33_L9CF01BK/1.jpg', 'images/produk/id33_L9CF01BK/2.jpg', 'images/produk/id33_L9CF01BK/3.jpg', 'images/produk/id33_L9CF01BK/4.jpg', 'images/produk/id33_L9CF01BK/5.jpg', 'images/produk/id33_L9CF01BK/6.jpg', 'images/produk/id33_L9CF01BK/7.jpg', 'images/produk/id33_L9CF01BK/8.jpg'], 
        description: {
            intro: 'Pilihan cerdas untuk MacBook Air M2. Unit ini dalam kondisi istimewa, fisik 95% mulus dengan baterai 100% (CC sangat rendah: 52). Nikmati desain modern, kecepatan M2, dan kenyamanan MagSafe. Sebuah paket komplit bernilai tinggi untuk Anda.',
            specs: ['Chip: Apple M2 (8-core CPU, 8-core GPU)', 
                    'Layar: 13.6-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 52',
                        'BH: 100%',
                        'Color: Silver' ]
        },
        pros: ['Processor Super Kencang Anti Panas',
                'Layar Jernih, Terang dan tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Normal dan Bass Mantap',
                'Redesign terbaru Macbook Air, lebih Modern dan Catchy',
                'Baterai tahan sangat lama (diatas 10 jam pemakaian ringan)',
                'Charging Menggunakan Magsafe'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air M2',
                'Magsafe Power Adapter',
                'Magsafe Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },
    // Produk 34
    { 
        id: 34, kategori: 'Mac', name: 'Macbook Air 13" Intel Core i3 (2020) - Space Grey', specs: '8GB RAM, 256GB SSD', 
        price: 6800000, stock: 2, grade: 'A', sku: '7RCF3ESV',  sold: 66,
        images: ['images/produk/id34_7RCF3ESV/1.jpg', 'images/produk/id34_7RCF3ESV/2.jpg', 'images/produk/id34_7RCF3ESV/3.jpg', 'images/produk/id34_7RCF3ESV/4.jpg', 'images/produk/id34_7RCF3ESV/5.jpg', 'images/produk/id34_7RCF3ESV/6.jpg', 'images/produk/id34_7RCF3ESV/7.jpg'], 
        description: {
            intro: 'MacBook Air 2020 modern yang super portabel. Kondisi sangat baik, fisik 95% mulus dengan baterai sehat 86%. Ditenagai Intel i3, laptop ini andal untuk semua tugas harian Anda. Nilai terbaik untuk mendapatkan laptop Apple modern dengan harga terjangkau.',
            specs: ['Chip: Intel Core i3 @1.1Ghz', 
                    'Layar: 13.3-inch Retina display',
                    'Memori: 8GB RAM terpadu', 
                    'Penyimpanan: 256GB SSD',
                        'CC: 152',
                        'BH: 86%',
                        'Color: Space Grey' ]
        },
        pros: ['Layar Jernih tanpa whitespot/deadpixel',
                'Kondisi fisik 95% mulus',
                'Speaker Jernih',
                'Layar Retina dengan warna akurat',
                'Tipis, ringan, dan mudah dibawa'],
        cons: ['Keterbatasan Port/Colokan (disarankan beli dongle terpisah)'],
        inTheBox: ['Unit MacBook Air 2020',
                'USB-C Power Adapter',
                'USB-C Charge Cable (2m)',
                'Kotak Original (jika tersedia)']
    },

    // =========IPHONE=========IPHONE=======IPHONE=======IPHONE========IPHONE
    // =========IPHONE=========IPHONE=======IPHONE=======IPHONE========IPHONE
    // =========IPHONE=========IPHONE=======IPHONE=======IPHONE========IPHONE
    // =========IPHONE=========IPHONE=======IPHONE=======IPHONE========IPHONE
    // =========IPHONE=========IPHONE=======IPHONE=======IPHONE========IPHONE
    
    // Tambahkan atau ganti produk iPhone Anda dengan struktur baru ini di dalam produk.js

// ... (data produk MacBook Anda tetap di atas sini)
        // produk 35
        {
        id: 35,
        name: 'iPhone 15 Pro',
        kategori: 'iPhone',
        basePrice: 18999000, // Harga untuk varian paling dasar
        images: {
                // Sediakan gambar untuk setiap warna
                'Natural Titanium': ['images/produk/id34_7RCF3ESV/1.jpg', 'images/produk/id34_7RCF3ESV/2.jpg', 'images/produk/id34_7RCF3ESV/3.jpg'],
                'Blue Titanium': ['images/produk/id34_7RCF3ESV/1.jpg', 'images/produk/id34_7RCF3ESV/2.jpg', 'images/produk/id34_7RCF3ESV/3.jpg'],
                'White Titanium': ['images/produk/id34_7RCF3ESV/1.jpg', 'images/produk/id34_7RCF3ESV/2.jpg', 'images/produk/id34_7RCF3ESV/3.jpg'],
                'Black Titanium': ['images/produk/id34_7RCF3ESV/1.jpg', 'images/produk/id34_7RCF3ESV/2.jpg', 'images/produk/id34_7RCF3ESV/3.jpg'],
        },
        // Daftar semua kemungkinan varian
        variants: [
                { sku: 'IP15P-NT-128', color: 'Natural Titanium', colorHex: '#8A8A85', storage: '128GB', priceModifier: 0, stock: 10, sold: 150 },
                { sku: 'IP15P-NT-256', color: 'Natural Titanium', colorHex: '#8A8A85', storage: '256GB', priceModifier: 2000000, stock: 8, sold: 120 },
                { sku: 'IP15P-BT-128', color: 'Blue Titanium', colorHex: '#2A3C4B', storage: '128GB', priceModifier: 0, stock: 15, sold: 90 },
                { sku: 'IP15P-BT-256', color: 'Blue Titanium', colorHex: '#2A3C4B', storage: '256GB', priceModifier: 2000000, stock: 5, sold: 75 },
                { sku: 'IP15P-WT-256', color: 'White Titanium', colorHex: '#F5F5F0', storage: '256GB', priceModifier: 2000000, stock: 12, sold: 85 },
                { sku: 'IP15P-BKT-128', color: 'Black Titanium', colorHex: '#4D4D4D', storage: '128GB', priceModifier: 0, stock: 0, sold: 110 },
        ],
        // Deskripsi umum untuk produk ini
        description: { intro: 'iPhone 15 Pro. Ditempa dalam titanium dan menampilkan Chip A17 Pro terobosan, tombol Tindakan yang dapat disesuaikan, dan sistem kamera Pro yang lebih kuat.', specs: ['Layar: 6.1-inch Super Retina XDR', 'Chip: A17 Pro', 'Kamera: Sistem kamera pro 48MP'], condition: 'Produk Baru, Garansi Resmi.' },
        pros: ['Bodi titanium premium yang ringan dan kuat', 'Performa A17 Pro untuk gaming dan tugas berat', 'Kualitas kamera terdepan', 'Port USB-C dengan kecepatan transfer tinggi'],
        cons: ['Harga premium', 'Daya tahan baterai standar'],
        inTheBox: ['Unit iPhone 15 Pro', 'Kabel Pengisi Daya USB-C (1 m)']
        },
        //produk 36
        {
        id: 36,
        name: 'iPhone 15 Pro Max',
        kategori: 'iPhone',
        basePrice: 22999000,
        images: {
                'Natural Titanium': ['images/produk/id34_7RCF3ESV/1.jpg', 'images/produk/id34_7RCF3ESV/2.jpg', 'images/produk/id34_7RCF3ESV/3.jpg'],
                'Blue Titanium': ['images/produk/id34_7RCF3ESV/1.jpg', 'images/produk/id34_7RCF3ESV/2.jpg', 'images/produk/id34_7RCF3ESV/3.jpg'],
        },
        variants: [
                { sku: 'IP15PM-NT-256', color: 'Natural Titanium', colorHex: '#8A8A85', storage: '256GB', priceModifier: 0, stock: 20, sold: 200 },
                { sku: 'IP15PM-NT-512', color: 'Natural Titanium', colorHex: '#8A8A85', storage: '512GB', priceModifier: 4000000, stock: 10, sold: 95 },
                { sku: 'IP15PM-BT-256', color: 'Blue Titanium', colorHex: '#2A3C4B', storage: '256GB', priceModifier: 0, stock: 18, sold: 130 },
        ],
        description: { intro: 'iPhone 15 Pro Max. Ditempa dalam titanium dan menampilkan Chip A17 Pro terobosan, tombol Tindakan yang dapat disesuaikan, dan sistem kamera Pro paling kuat yang pernah ada di iPhone dengan zoom optik 5x.', specs: ['Layar: 6.7-inch Super Retina XDR', 'Chip: A17 Pro', 'Kamera: Sistem kamera pro 48MP dengan 5x Telephoto'], condition: 'Produk Baru, Garansi Resmi.' },
        pros: ['Layar lebih besar dan imersif', 'Kamera dengan kemampuan zoom optik 5x', 'Daya tahan baterai terbaik', 'Performa A17 Pro'],
        cons: ['Ukuran besar mungkin tidak nyaman untuk semua orang', 'Harga sangat premium'],
        inTheBox: ['Unit iPhone 15 Pro Max', 'Kabel Pengisi Daya USB-C (1 m)']
        },
];